### PR TITLE
Formating DocStrings

### PR DESCRIPTION
**Pull request by abhimhamane**
I have documented the functions as per the standard format. 

+ I have also written some comments as `Todo` which I thought were important, like using BaseException all the time instead of in-built e `TypeError` or `ValueError`. 
+ I have moved the import statements out of function definition
+ There was one instances where a function was defined inside another function, and I believe that's not correct.
+ Some functions can have better input checking, its kind of inconsistent throughout the code-base.
+ I need to find the type of the input and output, I'll check that by using the module.

### CODE REVIEW

**Comment by mn5hk** [comment]
Hi @abhimhamane, thanks for a very detailed review and for making good edits to the document. I wanted to quickly check if you have tested the edited version of modules as well, especially since you have also edited some codes here?

Indeed, one of the functions is defined inside another function with a rather strange module workflow. Strangely enough, it is working as we want/expect it to. I personally chose not to touch it since it was working, so as not to risk getting the workflow order incorrect. Feel free to edit the codes a bit and to standardize it. 

However, perhaps, would it be more appropriate to merge it once the testing has been done?

My preference would be to for now, mainly complete the documentation and formatting issues. The code can be upgraded too, but I would prefer to merge it once we have rigorously tested the code again.

**Comment by abhimhamane** [comment]
Yeah @mn5hk you are right, it would be appropriate to merge only after testing. I've not tested the code since the function definition and import statements were the only major code changes rest all were doc-strings edits. I'll test to code and let you know.

Regards,
Abhishek

**Comment by abhimhamane** [comment]
I have tested the module after my edits, its seems to work. I tested the `01-tutorial` and its working fine.
Other notebooks like `validation_pyshbundle` have absolute paths and for them I do not have data, hence I did not try them out.

**Comment by mn5hk** [comment]
Well done @abhimhamane 

Thanks,
AS

**Pull request merged**
